---
title: "Faire tourner d'autres data"
author: "Vincyane Badouard"
date: "20/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(sf)
```

# Harvestable area (prospection units)
```{r}
ggplot() +
  geom_sf(data = HADP6[[1]],
          aes(alpha = Harvestable),
          fill = "olivedrab") +
  labs(alpha = "Harvestable") +
  labs(title = "P6 zones exploitables")

ggplot() +
  geom_sf(data = UPLisseesP6) +
  labs(title = "P6 UP lissées")

ggplot() +
  geom_sf(data = HADP16[[1]],
          aes(alpha = Harvestable),
          fill = "olivedrab") +
  labs(alpha = "Harvestable") +
  labs(title = "P16 zones exploitables")

ggplot() +
  geom_sf(data = UPLisseesP16) +
  labs(title = "P16 UP lissées")

```

# Tree selection
```{r}
ParacouP16_EFI3_BEcreux_designation <- treeselectionoutputsP16RIL3fuelhollow$inventory

write.csv2(ParacouP16_EFI3_BEcreux_designation, "D:/VSC Kourou/Dataexemple/ParacouP16_EFI3_BEcreux_designation.csv")
```

```{r}
# treeselectionoutputs <- treeselectionoutputsP6RIL2
# treeselectionoutputs <- treeselectionoutputsP6RIL2broken
# treeselectionoutputs <- treeselectionoutputsP6RIL3
# treeselectionoutputs <- treeselectionoutputsP6RIL3fuel
# treeselectionoutputs <- treeselectionoutputsP6RIL3fuelhollow
# 
# treeselectionoutputs <- treeselectionoutputsP16RIL2
# treeselectionoutputs <- treeselectionoutputsP16RIL2broken
# treeselectionoutputs <- treeselectionoutputsP16RIL3
# treeselectionoutputs <- treeselectionoutputsP16RIL3fuel
treeselectionoutputs <- treeselectionoutputsP16RIL3fuelhollow


NewInventory <- treeselectionoutputs$inventory


NonHarvestable <- sf::st_as_sf(
  dplyr::filter(NewInventory, LoggingStatus == "non-harvestable"),
  coords = c("Xutm", "Yutm")) %>% 
  st_set_crs(st_crs(HADP6[[1]]))

Harvestable <- sf::st_as_sf(
  dplyr::filter(NewInventory, LoggingStatus == "harvestable"),
  coords = c("Xutm", "Yutm")) %>% 
  st_set_crs(st_crs(HADP6[[1]]))

HarvestableUp <- sf::st_as_sf(
  dplyr::filter(NewInventory, LoggingStatus == "harvestableUp"),
  coords = c("Xutm", "Yutm")) %>% 
  st_set_crs(st_crs(HADP6[[1]]))

Selected <- sf::st_as_sf(
  dplyr::filter(NewInventory, Selected == "1"), coords = c("Xutm", "Yutm")) %>% 
  st_set_crs(st_crs(HADP6[[1]]))

Reserve <- sf::st_as_sf(
  dplyr::filter(NewInventory, LoggingStatus == "reserve"),
  coords = c("Xutm", "Yutm")) %>% 
  st_set_crs(st_crs(HADP6[[1]]))

Future <- sf::st_as_sf(
  dplyr::filter(NewInventory, LoggingStatus == "future"),
  coords = c("Xutm", "Yutm")) %>% 
  st_set_crs(st_crs(HADP6[[1]]))

ProbedHollow <- sf::st_as_sf(
  dplyr::filter(NewInventory, ProbedHollow == "1"), coords = c("Xutm", "Yutm")) %>% 
  st_set_crs(st_crs(HADP6[[1]]))


VisibleDefect <- sf::st_as_sf(
  dplyr::filter(NewInventory, VisibleDefect == "1"), coords = c("Xutm", "Yutm")) %>% 
  st_set_crs(st_crs(HADP6[[1]]))

```

```{r}
# enregistré avec une hauteur = 1000 or 1500
ggplot() +
  geom_sf(data = UPLisseesP16) +
  geom_sf(data = NonHarvestable,
          aes(colour = "Non-harvestable"), show.legend = "point") +
  geom_sf(data = VisibleDefect,
          aes(colour = "Visible defect"), show.legend = "point") +
  geom_sf(data = Future,
          aes(colour = "Future"), show.legend = "point", size = 4) +
  geom_sf(data = Reserve,
          aes(colour = "Reserve"), show.legend = "point", size = 4) +
  geom_sf(data = Harvestable,
          aes(colour = "Harvestable"), show.legend = "point", size = 4) +
  geom_sf(data = HarvestableUp,
          aes(colour = "HarvestableUp"), show.legend = "point", size = 4) +
  geom_sf(data = Selected,
          aes(colour = "Selected"), show.legend = "point") +
  geom_sf(data = ProbedHollow,
          aes(colour = "Probed hollow"), show.legend = "point") +
  
  scale_colour_manual(values = c("Non-harvestable" = "grey",
                                 "Visible defect" = "pink", "Harvestable" = "skyblue",
                                 "HarvestableUp" = "blue", "Selected" = "red", "Future" = "orange",
                                 "Reserve" = "purple", "Probed hollow" = "forestgreen")) +
  labs(color = "Logging status") +
  labs(title = "P16 désignation EFI3 + BE dont creux")
```

