---
title: "Secontrails plots"
author: "Vincyane Badouard"
date: "30/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r}
library(Maria)
library(ggplot2)
library(sf)
library(dplyr)
library(tibble)
```

# Data
```{r}
# save(secondtrails, file = "../data/secondtrails.Rdata")
data("HarvestablePolygons")
data(DTMParacou)
data(CreekDistances)
data(PlotMask)
data("MainTrails")
```

# Def UP
```{r}
HarvestableAreaOutputs <- harvestableareadefinition(
  topography = DTMParacou,
  creekdistances = CreekDistances,
  plotmask = PlotMask,
  scenario = "RIL2"
)
HarvesPolygons22 <-  HarvestableAreaOutputs$HarvestablePolygons
HarvesPolygons27 <-  HarvestableAreaOutputs27$HarvestablePolygons

HarvestableAreaOutputs27$HarvestableArea # 6.0683
HarvestableAreaOutputs$HarvestableArea # 6.0683


PlotSlope <-  HarvestableAreaOutputs$PlotSlope
```

# Outputs
```{r}
secondtrails$RawSecondTrails # 'non-smoothed secondary trails
class(secondtrails$RawSecondTrails) # SpatialLines (sp)
plot(st_as_sf(secondtrails$RawSecondTrails))

secondtrails$TrailsIdentity # information on sections of the trails
class(secondtrails$TrailsIdentity) # matrix

plot(secondtrails$SmoothedSecondTrails) # Smoothed Secondary Trails
class(secondtrails$SmoothedSecondTrails) # sfc_MULTIPOLYGON

secondtrails$TrailsDensity # TrailsDensity
class(secondtrails$TrailsDensity) # "units" ??? A mettre en numeric !

new_inventory <- secondtrails$inventory # inventory
class(secondtrails$inventory ) # data.frame

secondtrails$CostRasterAgg  # CostRasterMean. Sert à quoi ??
class(secondtrails$CostRasterAgg) # RasterLayer

```

# Plots
```{r}
ggplot() +
  # Harvestable zones
  geom_sf(data = HarvesPolygons27,
          aes(alpha = Harvestable),
          fill = "olivedrab") +
  labs(alpha = "Harvestable") +
  labs(title = "Paracou P6 zones exploitables 22 et 27% de pente")+
  geom_sf(data = HarvesPolygons22,
          aes(alpha = Harvestable),
          fill = "pink")
  
  # 2ndary trails
  geom_sf(data = st_as_sf(secondtrails$SmoothedSecondTrails), col = "darkgreen") +
  geom_sf(data = st_as_sf(secondtrails$RawSecondTrails), col = "red")

```

# With tree selection
```{r}
NewInventory <- treeselectionoutputs$inventory # objectivelax = TRUE


NonHarvestable <- sf::st_as_sf(
  dplyr::filter(NewInventory, LoggingStatus == "non-harvestable"),
  coords = c("Xutm", "Yutm")) %>% 
  st_set_crs(st_crs(HarvestablePolygons))

Harvestable <- sf::st_as_sf(
  dplyr::filter(NewInventory, LoggingStatus == "harvestable"),
  coords = c("Xutm", "Yutm")) %>% 
  st_set_crs(st_crs(HarvestablePolygons))

HarvestableUp <- sf::st_as_sf(
  dplyr::filter(NewInventory, LoggingStatus == "harvestableUp"),
  coords = c("Xutm", "Yutm")) %>%
  st_set_crs(st_crs(HarvestablePolygons))

Selected <- sf::st_as_sf(
  dplyr::filter(NewInventory, Selected == "1"), coords = c("Xutm", "Yutm")) %>% 
  st_set_crs(st_crs(HarvestablePolygons))

Reserve <- sf::st_as_sf(
  dplyr::filter(NewInventory, LoggingStatus == "reserve"),
  coords = c("Xutm", "Yutm")) %>% 
  st_set_crs(st_crs(HarvestablePolygons))

Future <- sf::st_as_sf(
  dplyr::filter(NewInventory, LoggingStatus == "future"),
  coords = c("Xutm", "Yutm")) %>%
  st_set_crs(st_crs(HarvestablePolygons))

ProbedHollow <- sf::st_as_sf(
  dplyr::filter(NewInventory, ProbedHollow == "1"), coords = c("Xutm", "Yutm")) %>% 
  st_set_crs(st_crs(HarvestablePolygons))


VisibleDefect <- sf::st_as_sf(
  dplyr::filter(NewInventory, VisibleDefect == "1"), coords = c("Xutm", "Yutm")) %>% 
  st_set_crs(st_crs(HarvestablePolygons))
```


# Plot with tree selection
```{r}
ggplot() +
  # Harvestable zones
  geom_sf(data = HarvestablePolygons,
          aes(alpha = Harvestable),
          fill = "olivedrab") +
  labs(alpha = "Harvestable") +
  labs(title = "P6 zones exploitables") +
  
  # 2ndary trails
  geom_sf(data = st_as_sf(secondtrails$SmoothedSecondTrails), col = "darkgreen") +
  geom_sf(data = st_as_sf(secondtrails$RawSecondTrails), col = "red") +
  
  # Tree selection
  # geom_sf(data = NonHarvestable,
  #         aes(colour = "Non-harvestable"), show.legend = "point") +
  geom_sf(data = VisibleDefect,
          aes(colour = "Visible defect"), show.legend = "point") +
  geom_sf(data = Future,
          aes(colour = "Future"), show.legend = "point", size = 4) +
  geom_sf(data = Reserve,
          aes(colour = "Reserve"), show.legend = "point", size = 4) +
  geom_sf(data = Harvestable,
          aes(colour = "Harvestable"), show.legend = "point", size = 4) +
  # geom_sf(data = HarvestableUp,
  #         aes(colour = "HarvestableUp"), show.legend = "point", size = 4) +
  geom_sf(data = Selected,
          aes(colour = "Selected"), show.legend = "point") +
  # geom_sf(data = ProbedHollow,
  #         aes(colour = "Probed hollow"), show.legend = "point") +
  geom_sf(data = MainTrails) +
  
  scale_colour_manual(values = c("Non-harvestable" = "grey",
                                 "Visible defect" = "pink", "Harvestable" = "skyblue",
                                 "HarvestableUp" = "blue", "Selected" = "red", "Future" = "orange",
                                 "Reserve" = "purple", "Probed hollow" = "forestgreen")) +
  labs(color = "Logging status") +
  labs(title = "Paracou P16 EFI3")
```

# Plot with treefelling
```{r}
NewInventory <- treefelling(new_inventory, scenario = "RIL3", fuel = "0",
                            winching = NULL, directionalfelling = NULL,
                            MainTrails = MainTrails, ScndTrail = st_as_sf(secondtrails[[3]]) ,
                            advancedloggingparameters = loggingparameters())

NewInventory_crs <- NewInventory %>%
  getgeometry(TreePolygon) %>%
  sf::st_set_crs(sf::st_crs(MainTrails)) # set a crs
```


```{r}
# enregistré avec une hauteur = 1000 or 1100 or 1500

ggplot() +
  # Harvestable zones
  geom_sf(data = HarvestablePolygons,
          aes(alpha = Harvestable),
          fill = "olivedrab") +
  labs(alpha = "Harvestable") +
  labs(title = "P6 zones exploitables") +
  
  # 2ndary trails
  geom_sf(data = st_as_sf(secondtrails$SmoothedTrails), col = "darkgreen") +
  geom_sf(data = st_as_sf(secondtrails$RawSecondTrails), col = "red") +
  
  
  # Tree selection
  # geom_sf(data = NonHarvestable,
  #         aes(colour = "Non-harvestable"), show.legend = "point") +
  geom_sf(data = VisibleDefect,
          aes(colour = "Visible defect"), show.legend = "point") +
  # geom_sf(data = Future,
  #         aes(colour = "Future"), show.legend = "point", size = 4) +
  geom_sf(data = Reserve,
          aes(colour = "Reserve"), show.legend = "point", size = 4) +
  geom_sf(data = Harvestable,
          aes(colour = "Harvestable"), show.legend = "point", size = 4) +
  # geom_sf(data = HarvestableUp,
  #         aes(colour = "HarvestableUp"), show.legend = "point", size = 4) +
  geom_sf(data = NewInventory_crs, # cuted trees
          alpha = 0.5, fill = "red") +
  geom_sf(data = Selected,
          aes(colour = "Selected"), show.legend = "point") +
  geom_sf(data = ProbedHollow,
          aes(colour = "Probed hollow"), show.legend = "point") +
  geom_sf(data = MainTrails) +
  
  scale_colour_manual(values = c("Non-harvestable" = "grey",
                                 "Visible defect" = "pink", "Harvestable" = "skyblue",
                                 "HarvestableUp" = "blue", "Selected" = "red", "Future" = "orange",
                                 "Reserve" = "purple", "Probed hollow" = "forestgreen")) +
  labs(color = "Logging status") +
  labs(title = "Paracou P6 EFI3")


write.csv2(NewInventory, "C:/Users/Vincyane/Documents/Maria-pictures/ParacouP6_EFI3.csv") #  D:/VSC Kourou/Dataexemple

```

